language: go

go:
  - 1.19
  - tip

before_install:
  - go get -t -v ./...

script:
  #- go test ./... -coverprofile=coverage.txt -covermode=atomic
  - go test ./... -coverprofile=coverage.txt -covermode=atomic -gcflags "all=-N -l"

after_success:
  - bash <(curl -s https://codecov.io/bash)
