name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Build
        run: go mod tidy && go build -v -o in-proxy ./examples/inproxy && go build -v -o out-proxy ./examples/outproxy

      - name: Unit Test
        run: go test -count 1 -v ./... -gcflags "all=-N -l" && go test -race -v ./... -gcflags "-l"
        #run: go test -count 1 -v ./...
        #go test -race ./... -gcflags "-l"

      - name: Benchmark Test
        working-directory: ./benchmark
        run: go test -count 1 -v -bench=. ./...
